name: bytepatch
version: "0.3.0"
synopsis: Patch byte-representable data in a bytestream.
description: Please see README.md.
extra-source-files:
- README.md
- CHANGELOG.md

github: raehik/bytepatch
license: MIT
license-file: LICENSE

category: CLI
maintainer: Ben Orchard <thefirstmuffinman@gmail.com>
author: Ben Orchard
tested-with: GHC >= 8.6 && < 9.2

# mostly Alexis King's 2018 recommended defaults
# (most can be replaced with GHC 9.2's GHC2021 language extension
default-extensions:
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- InstanceSigs
- MultiParamTypeClasses
- LambdaCase
- DeriveGeneric
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- GeneralizedNewtypeDeriving
- StandaloneDeriving
- BangPatterns
- KindSignatures
- TypeOperators
- TypeApplications

# we do a little type tomfoolery
- DataKinds
- TypeFamilies
- UndecidableInstances
- StandaloneKindSignatures
- RankNTypes
- ScopedTypeVariables

dependencies:
- base >= 4.12 && < 4.17
- vinyl
- mtl ^>= 2.2.2
- bytestring >= 0.10 && < 0.12
- text ^>= 1.2.4.1
- megaparsec >= 9.0 && < 9.3
- either ^>= 5.0.1.1
- aeson >= 1.5 && < 2.1 # TODO 2021-12-02 Stack still no 2.0 . Urgh.
- optics >= 0.3 && < 0.5
- generic-optics >= 2.1 && < 2.4 # TODO 2021-12-02 2.2 doesn't support GHC 9.2

library:
  source-dirs: src

executables:
  bytepatch:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytepatch
    - optparse-applicative >= 0.16.1 && < 0.17
    - yaml >= 0.11.7 && < 0.12

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    build-tools:
    - hspec-discover
    dependencies:
    - bytepatch
    - hspec
    - QuickCheck
