name: bytepatch
version: 0.4.1
synopsis: Patch byte-representable data in a bytestream
description: Please see README.md.
extra-source-files:
- README.md
- CHANGELOG.md
category: CLI
tested-with: GHC ==9.2.4
license: MIT
license-file: LICENSE

github: raehik/bytepatch
maintainer: Ben Orchard <thefirstmuffinman@gmail.com>
author: Ben Orchard

# TODO 2022-04-22 This will be supported eventually - I looked just now, and
# there was a fix 10 hours ago! But it'll take a while to trickle down into an
# hpack release, and then that release in Stack.
language: GHC2021

# raehik's extensions (GHC 9.2; last updated: 2022-06-15)
default-extensions:
# syntax that should be default
- EmptyCase
- LambdaCase
- InstanceSigs
- BangPatterns
- ExplicitNamespaces # 7.6

## deriving-related
- DerivingStrategies # 8.2
- DerivingVia # 8.6
- StandaloneDeriving
- DeriveAnyClass
- DeriveGeneric
- DeriveDataTypeable
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- DeriveLift

# features that should be default
- FlexibleContexts
- FlexibleInstances
- MultiParamTypeClasses
- GADTs
- PolyKinds
- RoleAnnotations # 7.8
- RankNTypes

# other features
- TypeApplications # 8.0
- DefaultSignatures
- TypeFamilies
- DataKinds

# other syntax
- MagicHash
- ImportQualifiedPost # 8.10
- StandaloneKindSignatures # 8.10

# essential, but can break things, so be wary
- ScopedTypeVariables # changes type var scoping quite dramatically
- TypeOperators # interferes with the old `*` type

# useful extensions to know about, but which must be specified on-demand
#- UndecidableInstances

ghc-options:
- -Wall

dependencies:
- base >= 4.12 && < 5
- vinyl ^>= 0.14.1
- mtl ^>= 2.3.1
- bytestring >= 0.10 && < 0.12
- text
- megaparsec >= 9.3 && < 9.7
- either ^>= 5.0.1.1
- aeson >= 2.1 && < 2.3
- text-short ^>= 0.1.5 # for text-2.0
- optics >= 0.3 && < 0.5
- generic-optics ^>= 2.2.1.0
- heystone ^>= 0.1.0
- blake3 ^>= 0.3
- memory ^>= 0.18
- singletons ^>= 3.0
- singletons-th ^>= 3.2 # 3.2 = GHC 9.6
- singletons-base ^>= 3.2
- binrep ^>= 0.5.0

library:
  source-dirs: src

executables:
  bytepatch:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytepatch
    - optparse-applicative ^>= 0.17
    - yaml ^>= 0.11.6.0
    - refined >= 0.7 && < 0.9

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    build-tools:
    - hspec-discover >= 2.10 && < 2.12
    dependencies:
    - bytepatch
    - hspec >= 2.10 && < 2.12
    - QuickCheck ^>= 2.14.3
