name: bytepatch
version: "0.3.1"
synopsis: Patch byte-representable data in a bytestream.
description: Please see README.md.
extra-source-files:
- README.md
- CHANGELOG.md
category: CLI
tested-with: GHC == 8.10.7, GHC == 9.0.1
license: MIT
license-file: LICENSE

github: raehik/bytepatch
maintainer: Ben Orchard <thefirstmuffinman@gmail.com>
author: Ben Orchard

# mostly Alexis King's 2018 recommended defaults
# (most can be replaced with GHC 9.2's GHC2021 language extension
default-extensions:
# essential
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- InstanceSigs
- MultiParamTypeClasses
- PolyKinds
- LambdaCase

# deriving-related
- DerivingStrategies
- StandaloneDeriving
- DeriveAnyClass
- DeriveGeneric
- DeriveDataTypeable
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- DeriveLift

# essential syntax but too recent
- ImportQualifiedPost # 8.10
- StandaloneKindSignatures # 8.10
- DerivingVia # 8.6

# less essential but still gimmes
- RoleAnnotations
- TypeApplications
- DataKinds
- TypeFamilies
- TypeOperators
- BangPatterns
- GADTs
- DefaultSignatures
- RankNTypes

# extra
- UndecidableInstances # honestly fine but...
- MagicHash # pretty much syntactic, but too weird
- ScopedTypeVariables # probs dangerous to have as default

dependencies:
- base >= 4.12 && < 4.17
- vinyl ^>= 0.14.1
- mtl ^>= 2.2.2
- bytestring >= 0.10 && < 0.12
- text ^>= 1.2.4.1
- megaparsec >= 9.0 && < 9.3
- either ^>= 5.0.1.1
- aeson ^>= 2.0
- optics >= 0.3 && < 0.5
- generic-optics ^>= 2.2.1.0
- keystone ^>= 0.1.1.0
- blake3 ^>= 0.2

# TODO
- memory

library:
  source-dirs: src

executables:
  bytepatch:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytepatch
    - optparse-applicative ^>= 0.17
    - yaml ^>= 0.11.6.0

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    build-tools:
    - hspec-discover >= 2.7 && < 2.10
    dependencies:
    - bytepatch
    - hspec >= 2.7 && < 2.10
    - QuickCheck ^>= 2.14.2
