name: bytepatch
version: "0.3.1"
synopsis: Patch byte-representable data in a bytestream.
description: Please see README.md.
extra-source-files:
- README.md
- CHANGELOG.md
category: CLI
tested-with: GHC == 8.10.7, GHC == 9.0.1
license: MIT
license-file: LICENSE

github: raehik/bytepatch
maintainer: Ben Orchard <thefirstmuffinman@gmail.com>
author: Ben Orchard

# mostly Alexis King's 2018 recommended defaults
# (most can be replaced with GHC 9.2's GHC2021 language extension
default-extensions:
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- InstanceSigs
- MultiParamTypeClasses
- LambdaCase
- DeriveGeneric
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- GeneralizedNewtypeDeriving
- StandaloneDeriving
- BangPatterns
- KindSignatures
- TypeOperators
- TypeApplications

# we do a little type tomfoolery
- DataKinds
- TypeFamilies
- UndecidableInstances
- StandaloneKindSignatures
- RankNTypes
- ScopedTypeVariables

# TODO 2022-02-02 locked out of GHC 9.2 by Vinyl not supporting it. Yikes
dependencies:
- base >= 4.12 && < 4.17
- vinyl ^>= 0.13.3
- mtl ^>= 2.2.2
- bytestring >= 0.10 && < 0.12
- text ^>= 1.2.4.1
- megaparsec >= 9.0 && < 9.3
- either ^>= 5.0.1.1
- aeson >= 1.5 && < 2.1 # TODO 2021-12-02 Stack still no 2.0 . Urgh.
- optics >= 0.3 && < 0.5
- generic-optics ^>= 2.1.0.0 # TODO ^>= 2.2.1.0 when GHC 9.2

library:
  source-dirs: src

executables:
  bytepatch:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytepatch
    - optparse-applicative ^>= 0.16.1
    - yaml ^>= 0.11.7.0

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    build-tools:
    - hspec-discover >= 2.7 && < 2.10
    dependencies:
    - bytepatch
    - hspec >= 2.7 && < 2.10
    - QuickCheck ^>= 2.14.2
